<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesPublishedByMonth.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/publishedByMonth.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/pictureGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphColumn.html');
include('../../../../app/controllers/news/graphObjectsPublishedByMonth.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
