<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/med/callApiArticlesPublishedByCustomer.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/med/publishedByCustomer.php');
include('../../mainHeaderMed.html');
include('../../../../app/models/navMedGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphColumn.html');
include('../../../../app/controllers/news/graphObjectsPublishedByCustomer.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
