<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/med/callApiArticlesPublishedByFreelance.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/med/publishedByFreelance.php');
include('../../mainHeaderMed.html');
include('../../../../app/models/navMedGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraph.html');
include('../../../../app/controllers/news/graphObjectsPublishedByFreelance.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
