<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesPublishedByCustomer.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/publishedByCustomer.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/pictureGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphArea.html');
include('../../../../app/controllers/news/graphObjectsPublishedByCustomer.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
