<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesPublishedByFreelance.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/publishedByFreelance.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/pictureGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphInverted.html');
include('../../../../app/controllers/news/graphObjectsPublishedByFreelance.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
