<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesReadByFreelance.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/readByFreelance.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphInverted.html');
include('../../../../app/controllers/news/graphObjectsReadByFreelance.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
