<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesReadByMostRead.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/readByMostRead.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphInverted.html');
include('../../../../app/controllers/news/graphObjectsReadByMostRead.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
