<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/news/callApiArticlesReadByMonth.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/news/readByMonth.php');
include('../../mainHeader.html');
include('../../../../app/models/navGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraph.html');
include('../../../../app/controllers/news/graphObjectsReadByMonth.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
