<?php
include('../../../../app/models/mainGraphNavModel.php');
include('../../../../app/services/med/callApiArticlesPublishedByMonth.php');
include('../../../../app/controllers/navController.php');
include('../../../../app/controllers/med/publishedByMonth.php');
include('../../mainHeaderMed.html');
include('../../../../app/models/navMedGeneric.php');
include('../../../../app/models/yearGeneric.php');
include('../../mainGraphInverted.html');
include('../../../../app/controllers/news/graphObjectsPublishedByMonth.php');
include('../../../../app/models/graphObjects.php');
include('../../mainFooter.html');
?>
